version: '3.4'

services:
  visitcard:
    image: visitcard
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:80
